name = "veganblatt-static"
compatibility_date = "2025-09-02"

[site]
bucket = "./public"

[[deploy]]
name = "production"
route = "veganblatt.com/*"

# Build configuration
[build]
command = "npm run build"
watch_paths = ["src/**/*"]